[돌아가기](../readme.md)

## 기본 에러와 사용자 정의 에러
```go
package main

import (
	"log"
	"os"
)

func main() {
	f, err := os.Open("./abc.txt")
	if err != nil {
		log.Println(err) // open ./abc.txt: The system cannot find the file specified
	} else {
		log.Println(f.Name())
	}

	// 새로 만든 에러로 타입 체크 시도
	err = &CustomError{
		Code:    "404",
		Message: "Not Found",
	}

	switch err.(type) {
	default:
		log.Println("no error")
	case *CustomError:
		log.Fatalln(err.Error()) // Fatal은 os.Exit(1)을 호출하므로 프로그램 종료
	case error:
		log.Fatalln(err.Error())
	}
}

type CustomError struct {
	Code    string
	Message string
}

func (e *CustomError) Error() string {
	return "[CustomError]" + e.Code + ":" + e.Message
}

```

## defer 와 panic
```go
package main

import (
	"os"
)

func main() {
	f, err := os.Open("./readme.md")
	if err != nil {
		panic(err) // 함수 실행 즉시 중지. 만약 recover 가 없다면 상위 콜스택으로 가다가 최후에는 프로그램이 종료됨.
	}

	// defer 는 함수가 종료되기 직전에 실행된다. java 의 finally 와 개념이 유사하다.
	defer f.Close()

	// 파일 read
	bytes := make([]byte, 1024)
	count, err := f.Read(bytes)
	if err != nil {
		panic(err)
	}
	println(count, string(bytes))
}

```

## recover
```go
package main

import "os"

func main() {
	openFile("test.txt")
	println("abcd") // 실행됨.
}

func openFile(fileName string) []byte {
	defer func() {
		if r := recover(); r != nil {
			println("Recover Complete", r)
		}
	}()

	f, err := os.Open(fileName)
	if err != nil {
		panic(err)
	}

	defer f.Close()

	bytes := make([]byte, 1024)
	_, err = f.Read(bytes)
	return bytes
}

```

## recover (상위 콜스택에서 하는 방법)
```go
package main

import "os"

func main() {
	defer func() {
		if r := recover(); r != nil {
			println("Recover Complete", r)
		}
	}() // 만약 openFile 보다 뒤에 있다면 recover 가 실행되지 않는다. 왠만하면 함수 내에서 해결하도록 하자.

	openFile("test.txt")
	println("abcd") // 실행 안됨.
}

func openFile(fileName string) []byte {
	f, err := os.Open(fileName)
	if err != nil {
		panic(err)
	}

	defer f.Close()

	bytes := make([]byte, 1024)
	_, err = f.Read(bytes)
	return bytes
}

```